### ISSUE TITLE
gitlab_group_share_group without expiration date gives nil pointer reference

### ISSUE THREAD

**Issue by valvin1** [gitlabhq/terraform-provider-gitlab#524]
### Terraform Version
Terraform v0.14.5
### Affected Resource(s)
- gitlab_group_share_group

### Terraform Configuration Files
```hcl
resource "gitlab_group_share_group" "my_group_share_group" {
  group_id       = data.gitlab_group.my_group.id
  share_group_id = gitlab_group.my_share_group.id
  group_access      = "maintainer"
}
```

### Debug Output
```
rpc error: code = Unavailable desc = transport is closing
```

### Panic Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: runtime error: invalid memory address or nil pointer dereference
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe10f02]
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: goroutine 45 [running]:
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: github.com/gitlabhq/terraform-provider-gitlab/gitlab.resourceGitlabGroupShareGroupRead(0xc0001aa770, 0x104d4e0, 0xc000634000, 0x2, 0x2)
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	github.com/gitlabhq/terraform-provider-gitlab/gitlab/resource_gitlab_group_share_group.go:108 +0x432
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: github.com/gitlabhq/terraform-provider-gitlab/gitlab.resourceGitlabGroupShareGroupCreate(0xc0001aa770, 0x104d4e0, 0xc000634000, 0x2, 0x1aebd00)
2021-01-25T08:12:20.034Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	github.com/gitlabhq/terraform-provider-gitlab/gitlab/resource_gitlab_group_share_group.go:76 +0x4fb
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000079b90, 0xc0006b8050, 0xc0006a83a0, 0x104d4e0, 0xc000634000, 0xf68601, 0xc0005e7888, 0xc0006a53e0)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x365
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00007e080, 0xc00062fa10, 0xc0006b8050, 0xc0006a83a0, 0xc0006b41a8, 0xc00000eab8, 0xf6a540)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x99
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e138, 0x1368780, 0xc0006a4b70, 0xc0001aa2a0, 0xc00000e138, 0x0, 0xc0002b3b78)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10b4de0, 0xc00000e138, 0x1368780, 0xc0006a4b70, 0xc0003ad980, 0x0, 0x1368780, 0xc0006a4b70, 0xc0000ca9a0, 0xd3)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001380, 0x1372a20, 0xc0000ad200, 0xc00010b200, 0xc000086cf0, 0x1ab1600, 0x0, 0x0, 0x0)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: google.golang.org/grpc.(*Server).handleStream(0xc000001380, 0x1372a20, 0xc0000ad200, 0xc00010b200, 0x0)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036240, 0xc000001380, 0x1372a20, 0xc0000ad200, 0xc00010b200)
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-25T08:12:20.035Z [DEBUG] plugin.terraform-provider-gitlab_v3.4.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2021-01-25T08:12:20.036Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/01/25 08:12:20 [DEBUG] gitlab_group_share_group.***_devops: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_devops encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_devops
2021/01/25 08:12:20 [TRACE] EvalApplyProvisioners: gitlab_group_share_group.***_devops has no state, so skipping provisioners
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_devops encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [DEBUG] gitlab_group_share_group.***_apis_build: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_apis_build encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_apis_build
2021/01/25 08:12:20 [TRACE] EvalApplyProvisioners: gitlab_group_share_group.***_apis_build has no state, so skipping provisioners
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_apis_build encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [DEBUG] gitlab_group_share_group.***_apis_devops: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_apis_build
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_apis_devops encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_apis_devops
2021/01/25 08:12:20 [TRACE] EvalApplyProvisioners: gitlab_group_share_group.***_apis_devops has no state, so skipping provisioners
2021/01/25 08:12:20 [TRACE] vertex "gitlab_group_share_group.***_apis_build": visit complete
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_apis_devops encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_apis_devops
2021/01/25 08:12:20 [TRACE] vertex "gitlab_group_share_group.***_apis_devops": visit complete
2021/01/25 08:12:20 [DEBUG] gitlab_group_share_group.***_build: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_devops
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_build encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [TRACE] vertex "gitlab_group_share_group.***_devops": visit complete
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_build
2021/01/25 08:12:20 [TRACE] EvalApplyProvisioners: gitlab_group_share_group.***_build has no state, so skipping provisioners
2021/01/25 08:12:20 [TRACE] EvalMaybeTainted: gitlab_group_share_group.***_build encountered an error during creation, so it is now marked as tainted
2021/01/25 08:12:20 [TRACE] EvalWriteState: removing state object for gitlab_group_share_group.***_build
2021/01/25 08:12:20 [TRACE] vertex "gitlab_group_share_group.***_build": visit complete
2021/01/25 08:12:20 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/25 08:12:20 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/gitlabhq/gitlab\"] (close)" errored, so skipping
2021/01/25 08:12:20 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-01-25T08:12:20.037Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/gitlabhq/gitlab/3.4.0/linux_amd64/terraform-provider-gitlab_v3.4.0 pid=1656 error="exit status 2"
2021-01-25T08:12:20.039Z [DEBUG] plugin: plugin exited
```

### Expected Behavior
Group share should be applied and state updated.

### Actual Behavior

Group share are well created on Gitlab side but state is not update because of the crash.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a a `gitlab_group_share_group` without expiration date
2. `terraform apply`

It looks issue is related to this [line](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_group_share_group.go#L108) on which the optional possibility of `ExpiresAt` is not taken as it looks to be [here](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_group_membership.go#L154)

**Comment by timofurrer** [comment]
This has been fixed with #555.
